Repository kitworks-kiring/kiring-frontend, pull requests merged in 2025-06, with the labels that each got.

#36 [플레이스] 레스토랑 리스트 (UI 작업) (#30)
  src/app/(full-layout)/(main)/components/recommend-section/place-card.tsx
  src/app/(header-layout)/place/components/PlaceContent.tsx
  src/app/(header-layout)/place/components/RestaurantCard.tsx
  src/app/(header-layout)/place/components/RestaurantContents.tsx
  src/app/(header-layout)/place/components/RestaurantWideCard.tsx
  src/app/(header-layout)/place/components/SortSelectBox.tsx
  src/app/(header-layout)/place/components/TrailContents.tsx
  src/app/(header-layout)/place/constants.ts
  src/app/(header-layout)/place/mock/restaurant.ts
  src/app/(header-layout)/place/page.tsx
  src/app/layout.tsx
  src/assets/like-button.svg
  src/assets/liked-button.svg
  src/assets/place-calendar.svg
  src/components/layout/Header/index.tsx
  src/components/layout/Navigation/index.tsx
  src/components/tabs/BubbleTab/index.tsx
  src/components/tabs/BubbleTab/useSingleSelect.ts
  src/components/tabs/DefaultTab/index.tsx
  src/components/tabs/DefaultTab/useTab.ts
  src/styles/utilities.css
Labels: feature, enhancement

#43 실시간 / 시간표 버튼 인터렉션 추가 #42
  src/app/(full-layout)/transit/components/subway/RealtimeHeader.tsx
  src/app/(full-layout)/transit/components/subway/SubwayContents.tsx
Labels: feature

#48 [플레이스] 레스토랑 카카오맵 UI 기능 초안 및 퍼블리싱 작업 (#39)
  package.json
  src/app/(full-layout)/transit/components/subway/SubwayContents.tsx
  src/app/(header-layout)/place/components/PlaceContent.tsx
  src/app/(header-layout)/place/components/restaurant/NarrowCard.tsx
  src/app/(header-layout)/place/components/restaurant/RestaurantContents.tsx
  src/app/(header-layout)/place/components/restaurant/RestaurantMap.tsx
  src/app/(header-layout)/place/components/restaurant/SortSelectBox.tsx
  src/app/(header-layout)/place/components/restaurant/WideCard.tsx
  src/app/(header-layout)/place/components/trail/TrailContents.tsx
  src/app/(header-layout)/place/mock/restaurant.ts
  src/app/(header-layout)/place/types/restaurantType.ts
  src/app/layout.tsx
  src/assets/ico-narrow.svg
  src/assets/ico-wide.svg
  src/components/layout/Header/index.tsx
  src/components/tabs/BubbleTab/index.tsx
  src/components/tabs/DefaultTab/index.tsx
  src/utils/calcDistance.ts
  tsconfig.json
  yarn.lock
Labels: feature

#49 [교통] 따릉이 탭 생성 및 지하철 탭 고도화 (#47)
  src/app/(full-layout)/(main)/components/section-header.tsx
  src/app/(full-layout)/transit/components/bicycle/BicycleContents.tsx
  src/app/(full-layout)/transit/components/bicycle/BicycleGrid.tsx
  src/app/(full-layout)/transit/components/subway/DirectionGrid.tsx
  src/app/(full-layout)/transit/components/subway/GroupHeader.tsx
  src/app/(full-layout)/transit/components/subway/SubwayContents.tsx
  src/app/(full-layout)/transit/types/bicycleType.ts
  src/app/api/bicycle/route.ts
  src/assets/arrow-left.svg
  src/assets/arrow-right.svg
  src/assets/arrow-tail-right.svg
  src/assets/ico-bicycle-logo.svg
  src/assets/ico-bicycle.svg
  src/assets/ico-main-arrow-right.svg
  src/assets/ico-refresh.svg
  src/assets/ico-subway-express.svg
  src/assets/ico-walking.svg
  src/components/tabs/BubbleTab/index.tsx
  src/components/tabs/DefaultTab/index.tsx
  src/styles/utilities.css
  src/utils/calcDistance.ts
Labels: feature

#64 [교통] lint error 해결 (#62)
  src/app/(full-layout)/transit/components/bus/BusContents.tsx
  src/app/api/bus/route.ts
Labels: bug

#66 [공통] Github Actions 사용 EC2 배포 설정 (#65)
  .github/workflows/develop.yml
  dockerfile
Labels: feature

#67 [공통] 카카오 동의항목 심사 대응 로그인 페이지 및 푸터 개인정보/이용약관 링크 추가 (#58)
  src/app/(full-layout)/(main)/components/footer.tsx
  src/app/(no-layout)/(auth)/login/components/LoginPage.tsx
Labels: enhancement, chore

#70 [공통] Github Actions 사용 개발계 변경 시 자동 Sync Fork (#69)
  .github/workflows/develop_sync_fork.yml
Labels: feature

#72 [캘린더] 캘린더 UI 구현 및 API 연동 (#53)
  package.json
  src/app/(full-layout)/calendar/components/CalendarContents.tsx
  src/app/(full-layout)/calendar/components/DayScheduleList.tsx
  src/app/(full-layout)/calendar/components/react-calendar.css
  src/app/(full-layout)/calendar/constants.ts
  src/app/(full-layout)/calendar/page.tsx
  src/app/(full-layout)/calendar/types/calendarType.ts
  src/app/(header-layout)/place/components/PlaceContents.tsx
  src/app/(header-layout)/place/components/restaurant/SortSelectBox.tsx
  src/app/(header-layout)/place/page.tsx
  src/app/not-found.tsx
  src/assets/ico-birthday.svg
  src/assets/ico-dinner.svg
  src/assets/ico-empty.svg
  src/assets/ico-holiday.svg
  src/assets/ico-notice.svg
  src/assets/ico-study.svg
  src/assets/status/coming-soon.png
  src/assets/status/not-found.png
  src/components/status/ComingSoon/index.tsx
  src/lib/dayjs.ts
  src/services/calendar.ts
  yarn.lock
Labels: feature

#73 [메인] 로그인 전 / 후 UI 구성 (#68)
  src/app/(full-layout)/(main)/components/SectionHeader.tsx
  src/app/(full-layout)/(main)/components/WeeklyScheduleSection.tsx
  src/app/(full-layout)/(main)/components/intro-section.tsx
  src/app/(full-layout)/(main)/components/introSection/IntroSection.tsx
  src/app/(full-layout)/(main)/components/introSection/Popup.tsx
  src/app/(full-layout)/(main)/components/member-section.tsx
  src/app/(full-layout)/(main)/components/memberSection/MemberSection.tsx
  src/app/(full-layout)/(main)/components/memberSection/TeamSelector.tsx
  src/app/(full-layout)/(main)/components/recommendSection/PlaceCard.tsx
  src/app/(full-layout)/(main)/components/recommendSection/RecommendSection.tsx
  src/app/(full-layout)/(main)/components/weekly-schedule-section.tsx
  src/app/(full-layout)/(main)/constants.ts
  src/app/(full-layout)/(main)/page.tsx
  src/app/(full-layout)/(main)/types/member.ts
  src/assets/ico-close.svg
  src/assets/ico-paper-airplane.svg
  src/assets/intro-kiring-ring.svg
  src/assets/intro-kiring.svg
  src/components/layout/Header/index.tsx
  src/services/members.ts
Labels: feature

#75 [커뮤니티] 팀 구성원 UI 구성 (#74)
  src/app/(full-layout)/(main)/components/memberSection/MemberSection.tsx
  src/app/(full-layout)/(main)/constants.ts
  src/app/(full-layout)/(main)/page.tsx
  src/app/(full-layout)/(main)/types/member.ts
  src/app/(full-layout)/community/components/CommunityContents.tsx
  src/app/(full-layout)/community/components/members/MembersContents.tsx
  src/app/(full-layout)/community/page.tsx
  src/app/(full-layout)/constants.ts
  src/components/layout/Navigation/index.tsx
  src/middleware.ts
  src/services/members.ts
Labels: feature

#82 [캘린더] 로그인 상태에 따른 UI 분기 처리 (#81)
  package-lock.json
  src/app/(full-layout)/calendar/components/CalendarContents.tsx
  src/app/(full-layout)/calendar/components/DayScheduleList.tsx
  src/app/(full-layout)/community/components/CommunityContents.tsx
  src/app/(full-layout)/transit/components/subway/SubwayContents.tsx
  src/app/(full-layout)/transit/constants.ts
  src/components/tabs/DefaultTab/index.tsx
Labels: enhancement

#86 [공통] 미들웨어 로그인/액세스 토큰 검증 시 방어 로직 추가 (#83)
  src/app/(no-layout)/(auth)/login/callback/components/LoginCallbackPage.tsx
  src/middleware.ts
Labels: bug

#89 [플레이스] 레스토랑 API 연동 및 무한스크롤 적용 (#54)
  src/app/(full-layout)/(main)/components/recommendSection/RecommendSection.tsx
  src/app/(full-layout)/community/components/members/MembersContents.tsx
  src/app/(header-layout)/place/components/restaurant/NarrowCard.tsx
  src/app/(header-layout)/place/components/restaurant/RestaurantContents.tsx
  src/app/(header-layout)/place/components/restaurant/RestaurantMap.tsx
  src/app/(header-layout)/place/constants.ts
  src/app/(header-layout)/place/mock/restaurant.ts
  src/app/(header-layout)/place/types/restaurantType.ts
  src/components/ui/LikeToggleButton/index.tsx
  src/middleware.ts
Labels: feature

#94 [종이 비행기 팝업] 메인 / 프로필 페이지 종이비행기 팝업 작업 (#93)
  src/app/(full-layout)/(main)/components/introSection/IntroSection.tsx
  src/app/(full-layout)/(main)/components/introSection/Popup.tsx
  src/app/(header-layout)/profile/components/plane/PlaneMessageCard.tsx
  src/app/(header-layout)/profile/components/plane/PlaneSection.tsx
  src/app/(header-layout)/profile/constants.ts
  src/assets/ico-receive-paper-airplane.svg
Labels: feature, enhancement

#96 [플레이스] 지도-레스토랑 리스트 연동 UI/UX 리뉴얼 (#91)
  src/app/(full-layout)/(main)/components/recommendSection/PlaceCard.tsx
  src/app/(header-layout)/place/components/restaurant/NarrowCard.tsx
  src/app/(header-layout)/place/components/restaurant/NarrowSkeleton.tsx
  src/app/(header-layout)/place/components/restaurant/RestaurantContents.tsx
  src/app/(header-layout)/place/components/restaurant/RestaurantMap.tsx
  src/app/(header-layout)/place/components/restaurant/SortSelectBox.tsx
  src/app/(header-layout)/place/components/restaurant/WideCard.tsx
  src/app/(header-layout)/place/components/restaurant/WideSkeleton.tsx
  src/app/(header-layout)/place/types/restaurantType.ts
  src/app/globals.css
  src/assets/restaurant/ico-gps.svg
  src/assets/restaurant/ico-list-more.svg
  src/assets/restaurant/ico-list.svg
  src/assets/restaurant/ico-map.svg
  src/assets/restaurant/ico-narrow.svg
  src/assets/restaurant/ico-reload.svg
  src/assets/restaurant/ico-wide.svg
  src/components/layout/Header/index.tsx
  src/components/layout/Navigation/constants.ts
  src/components/tabs/BubbleTab/index.tsx
  src/components/ui/LikeToggleButton/index.tsx
  src/services/restaurant.ts
  src/styles/animations/toast.css
  src/utils/calcDistance.ts
Labels: bug, enhancement

#103 [메인] 디테일 작업 (#102)
  src/app/(full-layout)/(main)/components/NewsModal.tsx
  src/app/(full-layout)/(main)/components/SectionHeader.tsx
  src/app/(full-layout)/(main)/components/introSection/IntroSection.tsx
  src/app/(full-layout)/(main)/components/introSection/Popup.tsx
  src/app/(full-layout)/(main)/components/recommendSection/PlaceCard.tsx
  src/app/(full-layout)/(main)/components/recommendSection/RecommendSection.tsx
  src/app/(full-layout)/(main)/page.tsx
  src/app/(header-layout)/profile/components/plane/PlaneSection.tsx
  src/assets/news/open-event.png
Labels: feature, enhancement

#104 [캘린더] 월별 데이터 호출 로직 수정 및 키링 이벤트 데이터 추가 (#97)
  src/app/(full-layout)/(main)/components/WeeklyScheduleSection.tsx
  src/app/(full-layout)/calendar/components/CalendarContents.tsx
  src/app/(full-layout)/calendar/components/DayScheduleList.tsx
  src/app/(full-layout)/calendar/constants.ts
  src/app/(full-layout)/calendar/types/calendarType.ts
  src/app/(full-layout)/calendar/util/sortEvents.ts
Labels: enhancement

#105 [프로필/종이비행기] 프로필 상세, 바텀시트, 웰컴 UX 개선 및 토큰/폰트 설정 개선 (#95)
  src/app/(full-layout)/(main)/components/memberSection/MemberSection.tsx
  src/app/(full-layout)/community/components/members/MembersContents.tsx
  src/app/(full-layout)/transit/components/subway/RealtimeHeader.tsx
  src/app/(header-layout)/mypage/components/plane/PlaneSection.tsx
  src/app/(header-layout)/profile/[memberId]/page.tsx
  src/app/(header-layout)/profile/components/MembersContent.tsx
  src/app/(header-layout)/profile/components/MypageContent.tsx
  src/app/(header-layout)/profile/components/memberinfo/MemberInfoSection.tsx
  src/app/(header-layout)/profile/components/plane/PlaneBottomSheet.tsx
  src/app/(header-layout)/profile/components/plane/PlaneMessageCard.tsx
  src/app/(header-layout)/profile/components/plane/PlaneSection.tsx
  src/app/(no-layout)/(auth)/login/callback/components/LoginCallbackPage.tsx
  src/app/(no-layout)/(auth)/welcome/components/WelcomePage.tsx
  src/app/(no-layout)/plane/components/PlaneWriteStep.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/components/layout/Header/index.tsx
  src/stores/login.ts
  src/styles/animations/plane.css
Labels: enhancement

#109 [공통] 프로젝트 pwa 세팅
  next.config.ts
  package.json
  public/icons/icon-192x192.png
  public/icons/icon-512x512.png
  public/manifest.json
  public/sw.js
  public/workbox-1bb06f5e.js
  src/app/layout.tsx
  yarn.lock
Labels: feature

#112 [공통] OG Image 설정 (#111)
  public/images/og-image.png
  src/app/layout.tsx
Labels: enhancement

#113 [공통] 뷰저블 연동 (#98)
  src/app/analytics.tsx
  src/app/layout.tsx
Labels: docs

#115 [메인페이지] UI/UX 개선 및 환경 변수 관리 리팩토링 (#114)
  src/app/(full-layout)/(main)/components/WeeklyScheduleSection.tsx
  src/app/(full-layout)/(main)/components/introSection/IntroSection.tsx
  src/app/(full-layout)/(main)/components/memberSection/MemberSection.tsx
  src/app/(header-layout)/place/components/restaurant/RestaurantContents.tsx
  src/components/layout/Header/index.tsx
Labels: enhancement
