Repository kitworks-kiring/kiring-frontend, pull requests merged in 2025-05, with the labels that each got.

#10 [공통] axios 인터셉터 구성 및 http 메서드 추상화 #9
  package.json
  src/lib/api/axios.ts
  src/lib/api/client.ts
  yarn.lock
Labels: feature

#11 [공통] 피그마 디자인 토큰 연동 및 디자인 시스템 설정
  .vscode/settings.json
  config/design-token.config.mjs
  package-lock.json
  package.json
  src/app/globals.css
  src/app/page.tsx
  src/styles/design-tokens.css
  tokens/design-token.json
  yarn.lock
Labels: docs

#13 [헤더/푸터] UI 작업 (#12)
  next.config.ts
  package.json
  src/app/layout.tsx
  src/assets/default-profile.svg
  src/assets/header-logo.svg
  src/assets/nav-calendar.svg
  src/assets/nav-community.svg
  src/assets/nav-home.svg
  src/assets/nav-place.svg
  src/assets/nav-transit.svg
  src/components/Header.tsx
  src/components/Navigation.tsx
  src/components/SvgButton.tsx
  yarn.lock
Labels: feature

#15 [버그] webpack svg 사용 관련 빌드 에러 bug 버그 #14
  next.config.ts
Labels: bug

#20 [백엔드] ERD 구성 및 supabase, prisma 연동 (#8)
  components.json
  package.json
  prisma/schema.prisma
  src/app/admin/page.tsx
  src/app/api/health/route.ts
  src/app/api/team/route.ts
  src/app/globals.css
  src/db/team.ts
  src/lib/api/client.ts
  src/lib/api/team.ts
  src/lib/cn.ts
  src/lib/prisma.ts
  src/lib/utils/responseStatus.ts
  src/lib/utils/wrapApiResponse.ts
  src/styles/utilities.css
  tailwind.config.js
  yarn.lock
Labels: feature

#25 [백엔드] Swagger 생성 (#24)
  package.json
  src/app/admin/page.tsx
  src/app/api/health/route.ts
  src/app/api/swagger-json/route.ts
  src/app/api/team/route.ts
  src/app/swagger/page.tsx
  src/components/LoadingSpinner.tsx
  src/lib/api/team.ts
  src/lib/swagger.ts
  src/lib/utils/wrapApiResponse.ts
  yarn.lock
Labels: docs

#33 [공통] 레이아웃 구조 분리 / 유틸리티 클래스 적용 및 해더 로직 수정
  src/app/(full-layout)/calendar/page.tsx
  src/app/(full-layout)/community/page.tsx
  src/app/(full-layout)/layout.tsx
  src/app/(full-layout)/page.tsx
  src/app/(full-layout)/transit/page.tsx
  src/app/(header-layout)/layout.tsx
  src/app/(header-layout)/place/constants.ts
  src/app/(header-layout)/place/page.tsx
  src/app/(no-layout)/layout.tsx
  src/app/layout.tsx
  src/components/layout/Header/index.tsx
  src/styles/utilities.css
Labels: enhancement

#34 [메인페이지] UI 작업 #16
  next.config.ts
  package.json
  src/app/(full-layout)/(main)/components/intro-section.tsx
  src/app/(full-layout)/(main)/components/member-section.tsx
  src/app/(full-layout)/(main)/components/recommend-section/place-card.tsx
  src/app/(full-layout)/(main)/components/recommend-section/recommend-section.tsx
  src/app/(full-layout)/(main)/components/section-header.tsx
  src/app/(full-layout)/(main)/components/weekly-schedule-section.tsx
  src/app/(full-layout)/(main)/page.tsx
  src/app/(full-layout)/page.tsx
  src/app/layout.tsx
  src/assets/arrow-header.svg
  src/assets/arrow-right.svg
  src/assets/intro-kiring.svg
  src/assets/like-button.svg
  src/assets/like.svg
  src/assets/unlike-button.svg
  src/components/layout/Header/index.tsx
  src/components/layout/Navigation/index.tsx
  yarn.lock
Labels: feature
